name: Upstream Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Upstream Kernel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex build-essential libncurses-dev libssl-dev wget curl git

      - name: Prepare Build Script
        run: chmod +x build.sh

      - name: Load Config (Optional)
        run: source config.env || true

      - name: Compile Kernel
        run: ./build.sh

      - name: Upload Kernel Output
        uses: actions/upload-artifact@v3
        with:
          name: kernel_output
          path: out/
